[WinEventLog://Application]
disabled = 0
index = soc_endpoint

[WinEventLog://Security]
disabled = 0
index = soc_endpoint

[WinEventLog://System]
disabled = 0
index = soc_endpoint

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
renderXml = true
index = soc_endpoint